/:
  controller: User
  action: home

/login:
  controller: User
  action: login

/home:
  controller: User
  action: home

/template:
  controller: User
  action: template

/dashboard:
  controller: Dashboard
  action: dashboard

/statistiques:
  controller: Dashboard
  action: stat

/inscription:
  controller: User
  action: signup

/connexion:
  controller: User
  action: signin

/cinema:
  controller: Cinema
  action: cinema

/salles:
  controller: Cinema
  action: salles
  
/addfilm:
  controller: Dashboard
  action: addfilm

/delete:
  controller: Dashboard
  action: deleteMovie

/users:
  controller: Dashboard
  action: users

/horraires:
  controller: Dashboard
  action: horraires