/login:
  controller: User
  action: login

/home:
  controller: User
  action: home

/template:
  controller: User
  action: template


/dashboard:
  controller: User
  action: dashboard

/statistiques:
  controller: User
  action: stat

/inscription:
  controller: User
  action: signup

/connexion:
  controller: User
  action: signin

/cinema:
  controller: Cinema
  action: cinema

/salles:
  controller: Cinema
  action: salles