############ Dashboard ###########

/dashboard:
  controller: Dashboard
  action: dashboard

/statistiques:
  controller: Dashboard
  action: stat

/horaires:
  controller: Dashboard
  action: horraires

############ User ############

/:
  controller: User
  action: home

/users:
  controller: User
  action: users

/delete-user:
  controller: User
  action: deleteUser

/edit-user:
  controller: User
  action: editUser

/show-user:
  controller: User
  action: showUser

/login:
  controller: User
  action: login

/register:
  controller: User
  action: register

/forget-password:
  controller: User
  action: forgetPassword

/reset-form-pwd:
  controller: User
  action: resetFormPwd

/home:
  controller: User
  action: home

/user-verif:
  controller: User
  action: accountActivation

/mail-not-checked:
  controller: User
  action: mailNotChecked

/session-not-start:
  controller: User
  action: sessionNotStart

/no-permission:
  controller: User
  action: noPermission

/report-user-comment:
  controller: User
  action: reportComment

########### Cinema #############

/cinema:
  controller: Cinema
  action: cinema

/ajout-cinema:
  controller: Cinema
  action: addCinema

/edit-cinema:
  controller: Cinema
  action: editCinema

/delete-cinema:
  controller: Cinema
  action: deleteCinema

/show-cinema:
  controller: Cinema
  action: showCinema

######## Salles #########

/salles:
  controller: Room
  action: room

/add-salle:
  controller: Room
  action: addRoom

/edit-salle:
  controller: Room
  action: editRoom

/delete-salle:
  controller: Room
  action: deleteRoom

######## Movie #########

/show-movie:
  controller: Movie
  action: showMovie

/delete-movie:
  controller: Movie
  action: deleteMovie

/edit-movie:
  controller: Movie
  action: editMovie

/addfilm:
  controller: Movie
  action: addFilm

/show-research:
  controller: Movie
  action: searchMovie

/show-searched:
  controller: Movie
  action: showSearched

########### Comment #############

/comments:
  controller: Comment
  action: comment

/show-comment: 
  controller: Comment
  action: showComment

/ajout-commentaire:
  controller: Comment
  action: addComment

/delete-commentaire:
  controller: Comment
  action: deleteComment

/edition-commentaire:
  controller: Comment
  action: editComment

########### Page #############

/pages:
  controller: Page
  action: Page

/delete-page:
  controller: Page
  action: deletePage

/edition-page:
  controller: Page
  action: editPage

/addpage:
  controller: Page
  action: addPage

/show-pages:
  controller: Page
  action: showPages

/delete-pages:
  controller: Page
  action: deletePage

/build-page:
  controller: Page
  action: buildPage

/show-custom-pages:
  controller: Page
  action: showCustomPages

/template:
  controller: Page
  action: templateCreate

/show-sections-page:
  controller: Page
  action: showSectionsPage

/show-components-page:
  controller: Page
  action: showComponentsPage

/edit-component-page:
  controller: Page
  action: editComponentPage

/delete-component-page:
  controller: Page
  action: deleteComponentPage

########### Component #############

/components:
  controller: component
  action: component

/ajout-component:
  controller: Component
  action: addComponent

/delete-component:
  controller: Component
  action: deleteComponent

/edition-component:
  controller: Component
  action: editComponent

  ########### Installer #############

/installation:
  controller: installer
  action: installer

############ Customization ##########

/personnalisation:
  controller: Custom
  action: custom


########### Reservation et Seances #############
/show-seances:
  controller: MovieReservation
  action: showSeances

/showReservation:
  controller: MovieReservation
  action: showReservation

/seances:
  controller: MovieReservation
  action: seances

/getSeances:
  controller: MovieReservation
  action: getSeances

/addSeance:
  controller: MovieSession
  action: addSeance

/reservation:
  controller: MovieReservation
  action: reservation

/getReservations:
  controller: MovieReservation
  action: getReservations

/deleteReservation:
  controller: MovieReservation
  action: deleteReservation

/edit-seance:
  controller: MovieSession
  action: editSeance

/delete-seance:
  controller: MovieSession
  action: deleteSeance
