/:
  controller: User
  action: landing

/login:
  controller: User
  action: login

/dashboard:
  controller: User
  action: dashboard

/statistiques:
  controller: User
  action: stat

/inscription:
  controller: User
  action: signup

/connexion:
  controller: User
  action: signin

/users:
  controller: User
  action: users