############ Dashboard ###########

/dashboard:
  controller: Dashboard
  action: dashboard

/suppression-film:
  controller: Dashboard
  action: deleteMovie

/edition-film:
  controller: Dashboard
  action: editMovie

/statistiques:
  controller: Dashboard
  action: stat

/ajout-film:
  controller: Dashboard
  action: addFilm

/users:
  controller: Dashboard
  action: users

/horaires:
  controller: Dashboard
  action: horraires

/addFilm:
  controller: Dashboard
  action: addFilm

############ User ############

/:
  controller: User
  action: home

/inscription:
  controller: User
  action: signup

/connexion:
  controller: User
  action: signin

/login:
  controller: User
  action: login

/home:
  controller: User
  action: home

/template:
  controller: User
  action: template


########### Cinema.php #############

/salles:
  controller: Cinema
  action: salles

/cinema:
  controller: Cinema
  action: cinema

/ajout-cinema:
  controller: Cinema
  action: addCinema

/edit-cinema:
  controller: Cinema
  action: editCinema

/addpage:
  controller: User
  action: addpage

/horraires:
  controller: Dashboard
  action: horraires

/delete-cinema:
  controller: Cinema
  action: deleteCinema

/show-movie:
  controller: Cinema
  action: showMovie
